id ="pico-8"
name ="Pico-8"
description = "Pico-8 support for Zed"
version = "0.0.1"
schema_version = 1
authors = ["Fu Munchy"]

[language_servers.pico8-ls]
name ="pico8-ls"
languages = ["Pico-8"]

[grammars.pico8]
repository = "https://github.com/paradoxskin/tree-sitter-pico8.git"
rev = "de2b8b0e20e6c1413870b237951cc704319d840c"
