# The following has been copied and adjusted from
# https://github.com/zed-extensions/lua/blob/main/languages/lua/config.toml
name = "Pico-8"
grammar = "lua"
path_suffixes = ["lua"]
line_comments = ["-- ", "--- "]
block_comment = ["--[ ","]"]
hard_tabs = true
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
collapsed_placeholder = "--[ ... ]--"
